package model.am.views;

import model.shared.extensions.ExtApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 11:42:41 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ExtApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Files1.
     * @return Files1
     */
    public FilesVOImpl getFiles1() {
        return (FilesVOImpl) findViewObject("Files1");
    }
}

