package model.am.views;

import model.shared.extensions.ExtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 11:43:18 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilesVOImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FilesVOImpl() {
    }
}

